In [2]:
import numpy as np

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Q1
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [5]:
#Q2
arr[arr%2!=0]=-1

In [6]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Q3
arr3=np.where(arr%2!=0,-1,arr2)

In [9]:
arr3

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Q4
arr2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
#Q5
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

In [13]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
c=np.vstack((a,b))

In [16]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
#Q6
d=np.hstack((a,b))

In [18]:
d

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
#Q7
a = np.array([1,2,3])

In [20]:
e=np.repeat(a,3)
f=np.tile(a,3)

In [21]:
e

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [22]:
f

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
g=np.concatenate((e,f))

In [24]:
g

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [25]:
#Q8
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [26]:
h=np.intersect1d(a,b)
h

array([2, 4])

In [27]:
#Q9
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])


In [28]:
I=np.setdiff1d(a, b)

In [29]:
I

array([1, 2, 3, 4])

In [30]:
#10
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)


(array([1, 3, 5, 7], dtype=int64),)

In [31]:
#11
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [32]:
b=np.where((a >= 5) & (a <= 10))

In [33]:
b

(array([1, 3, 4], dtype=int64),)

In [34]:
#Q12
arr = np.arange(9).reshape(3,3)

In [35]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr2=np.flip(arr,axis=0)

In [37]:
arr2

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [38]:
#IRIS DATASET

import pandas as pd 

In [39]:
from sklearn.datasets import load_iris 

In [40]:
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [41]:
#Q13
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [42]:
df.median()

sepal length (cm)    5.80
sepal width (cm)     3.00
petal length (cm)    4.35
petal width (cm)     1.30
dtype: float64

In [43]:
from statistics import stdev
stdev(df['sepal length (cm)'])

0.8280661279778629

In [44]:
#Q14
percentile5 = np.percentile(df['sepal length (cm)'],5)

In [45]:
percentile95 = np.percentile(df['sepal length (cm)'],95)

In [46]:
percentile95

7.254999999999998

In [47]:
percentile5

4.6

In [48]:
#Q15
c=pd.unique(df['sepal length (cm)'])

In [49]:
c

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [50]:
c.size

35

In [51]:
car93=pd.read_csv('Cars93.csv')

In [52]:
car93.head()

Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0           1        Acura  Integra    Small       12.9   15.9       18.8   
1           2        Acura   Legend  Midsize       29.2   33.9       38.7   
2           3         Audi       90  Compact       25.9   29.1       32.3   
3           4         Audi      100  Midsize       30.8   37.7       44.6   
4           5          BMW     535i  Midsize       23.7   30.0       36.2   

   MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0        25           31                None  ...          5    177   
1        18           25  Driver & Passenger  ...          5    195   
2        20           26         Driver only  ...          5    180   
3        19           26  Driver & Passenger  ...          6    193   
4        22           30         Driver only  ...          4    186   

   Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0        102     68           37            26.5         11.0    2705   
1        115     71           38            30.0         15.0    3560   
2        102     67           37            28.0         14.0    3375   
3        106     70           37            31.0         17.0    3405   
4        109     69           39            27.0         13.0    3640   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 28 columns]

In [53]:
#Q17
car93.isnull().sum()

Unnamed: 0             0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                0
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [54]:
#Q16
car93[car93['Rear.seat.room'].isnull()]

Unnamed: 0 Manufacturer     Model    Type  Min.Price  Price  Max.Price  \
18          19    Chevrolet  Corvette  Sporty       34.6   38.0       41.5   
56          57        Mazda      RX-7  Sporty       32.5   32.5       32.5   

    MPG.city  MPG.highway      AirBags  ... Passengers Length  Wheelbase  \
18        17           25  Driver only  ...          2    179         96   
56        17           25  Driver only  ...          2    169         96   

    Width  Turn.circle  Rear.seat.room Luggage.room  Weight   Origin  \
18     74           43             NaN          NaN    3380      USA   
56     69           37             NaN          NaN    2895  non-USA   

                  Make  
18  Chevrolet Corvette  
56          Mazda RX-7  

[2 rows x 28 columns]

In [55]:
car93[car93['Luggage.room'].isnull()]

Unnamed: 0 Manufacturer       Model    Type  Min.Price  Price  Max.Price  \
15          16    Chevrolet  Lumina_APV     Van       14.7   16.3       18.0   
16          17    Chevrolet       Astro     Van       14.7   16.6       18.6   
18          19    Chevrolet    Corvette  Sporty       34.6   38.0       41.5   
25          26        Dodge     Caravan     Van       13.6   19.0       24.4   
35          36         Ford    Aerostar     Van       14.5   19.9       25.3   
55          56        Mazda         MPV     Van       16.6   19.1       21.7   
56          57        Mazda        RX-7  Sporty       32.5   32.5       32.5   
65          66       Nissan       Quest     Van       16.7   19.1       21.5   
69          70   Oldsmobile  Silhouette     Van       19.5   19.5       19.5   
86          87       Toyota      Previa     Van       18.9   22.7       26.6   
88          89   Volkswagen     Eurovan     Van       16.6   19.7       22.7   

    MPG.city  MPG.highway      AirBags  ... Passengers Length  Wheelbase  \
15        18           23         None  ...          7    178        110   
16        15           20         None  ...          8    194        111   
18        17           25  Driver only  ...          2    179         96   
25        17           21  Driver only  ...          7    175        112   
35        15           20  Driver only  ...          7    176        119   
55        18           24         None  ...          7    190        110   
56        17           25  Driver only  ...          2    169         96   
65        17           23         None  ...          7    190        112   
69        18           23         None  ...          7    194        110   
86        18           22  Driver only  ...          7    187        113   
88        17           21         None  ...          7    187        115   

    Width  Turn.circle  Rear.seat.room Luggage.room  Weight   Origin  \
15     74           44            30.5          NaN    3715      USA   
16     78           42            33.5          NaN    4025      USA   
18     74           43             NaN          NaN    3380      USA   
25     72           42            26.5          NaN    3705      USA   
35     72           45            30.0          NaN    3735      USA   
55     72           39            27.5          NaN    3735  non-USA   
56     69           37             NaN          NaN    2895  non-USA   
65     74           41            27.0          NaN    4100  non-USA   
69     74           44            30.5          NaN    3715      USA   
86     71           41            35.0          NaN    3785  non-USA   
88     72           38            34.0          NaN    3960  non-USA   

                     Make  
15   Chevrolet Lumina_APV  
16        Chevrolet Astro  
18     Chevrolet Corvette  
25          Dodge Caravan  
35          Ford Aerostar  
55              Mazda MPV  
56             Mazda RX-7  
65           Nissan Quest  
69  Oldsmobile Silhouette  
86          Toyota Previa  
88     Volkswagen Eurovan  

[11 rows x 28 columns]

In [56]:
#Q18
car93.fillna(0)

Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0            1        Acura  Integra    Small       12.9   15.9       18.8   
1            2        Acura   Legend  Midsize       29.2   33.9       38.7   
2            3         Audi       90  Compact       25.9   29.1       32.3   
3            4         Audi      100  Midsize       30.8   37.7       44.6   
4            5          BMW     535i  Midsize       23.7   30.0       36.2   
..         ...          ...      ...      ...        ...    ...        ...   
88          89   Volkswagen  Eurovan      Van       16.6   19.7       22.7   
89          90   Volkswagen   Passat  Compact       17.6   20.0       22.4   
90          91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7   
91          92        Volvo      240  Compact       21.8   22.7       23.5   
92          93        Volvo      850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0         25           31                None  ...          5    177   
1         18           25  Driver & Passenger  ...          5    195   
2         20           26         Driver only  ...          5    180   
3         19           26  Driver & Passenger  ...          6    193   
4         22           30         Driver only  ...          4    186   
..       ...          ...                 ...  ...        ...    ...   
88        17           21                None  ...          7    187   
89        21           30                None  ...          5    180   
90        18           25                None  ...          4    159   
91        21           28         Driver only  ...          5    190   
92        20           28  Driver & Passenger  ...          5    184   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0         102     68           37            26.5         11.0    2705   
1         115     71           38            30.0         15.0    3560   
2         102     67           37            28.0         14.0    3375   
3         106     70           37            31.0         17.0    3405   
4         109     69           39            27.0         13.0    3640   
..        ...    ...          ...             ...          ...     ...   
88        115     72           38            34.0          0.0    3960   
89        103     67           35            31.5         14.0    2985   
90         97     66           36            26.0         15.0    2810   
91        104     67           37            29.5         14.0    2985   
92        105     69           38            30.0         15.0    3245   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88  non-USA  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 28 columns]

In [57]:
car93[car93['Rear.seat.room']==0]

Empty DataFrame
Columns: [Unnamed: 0, Manufacturer, Model, Type, Min.Price, Price, Max.Price, MPG.city, MPG.highway, AirBags, DriveTrain, Cylinders, EngineSize, Horsepower, RPM, Rev.per.mile, Man.trans.avail, Fuel.tank.capacity, Passengers, Length, Wheelbase, Width, Turn.circle, Rear.seat.room, Luggage.room, Weight, Origin, Make]
Index: []

[0 rows x 28 columns]

In [62]:
#19
c=pd.unique(df['sepal length (cm)'])
c

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [64]:
c.size

35

In [65]:
#20
df['petal length (cm)'].nlargest(2)

118    6.9
117    6.7
Name: petal length (cm), dtype: float64